# Generated by Django 5.2.4 on 2025-07-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresult',
            options={},
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='user',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='email',
            field=models.EmailField(default='abc@opentext.com', max_length=254),
        ),
    ]
