# Generated by Django 5.2.4 on 2025-07-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_question_correct_option_option_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
