# Generated by Django 5.2.4 on 2025-07-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_duration_minutes_quizaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='has_exited',
            field=models.BooleanField(default=False),
        ),
    ]
