# Generated by Django 5.2.4 on 2025-07-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizresult_has_exited'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizaccess',
            name='has_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
