# Generated by Django 5.2.4 on 2025-07-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizaccess_has_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='name',
            field=models.CharField(default='opentext', max_length=100),
        ),
    ]
