# Generated by Django 5.2.4 on 2025-07-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quizresult_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
