# Generated by Django 5.2.4 on 2025-07-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_question_options_question_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_leaderboard',
            field=models.BooleanField(default=True),
        ),
    ]
