# Generated by Django 5.2.4 on 2025-07-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quiz_show_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
