# Generated by Django 5.2.4 on 2025-07-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quiz_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=10)),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
    ]
